spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat
    username: chatuser
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml